version: "3"

#without reverse proxy
services:
  pihole:
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
      - 1.1.1.1
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - "67:67/udp"
      - '8081:80/tcp'
      - "443:443/tcp"
    volumes:
      - './pihole_configs/etc-pihole/:/etc/pihole/'
      - './pihole_configs/etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # run `touch ./var-log/pihole.log` first unless you like errors
      # - './var-log/pihole.log:/var/log/pihole.log'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
    #  - NET_ADMIN
    environment:
      ServerIP: 192.168.0.37
      TZ: 'Europe/London'
      WEBPASSWORD: 'qwerty8881212'
    restart: unless-stopped
  
  postgres_db:
    image: postgres
    container_name: postgres_db_cn
    restart: always
    volumes:
      - ./temp_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud_db
      - POSTGRES_USER=nextcloud_db_user
      - POSTGRES_PASSWORD=qwerty8881212
      - POSTGRES_HOST=localhost
  nextcloud_app:
    image: nextcloud
    container_name: nextcloud_og_cn
    restart: always
    ports:
      - 8082:80
    volumes:
      - ./temp_nextcloud:/var/www/html
      - ./temp_nextcloud/data:/var/www/html/data:rw
      - /home/vishal/Desktop/ext_HDD:/media/ext_hdd_1:rw
    depends_on:
      - postgres_db


#   Another container you might want to have running through the proxy
#   Note it also have ENV Vars like pihole and a host under pihole's extra_hosts
#  ghost:
#    image: fractalf/ghost
#    ports:
#      - '2368:2368/tcp'
#    volumes:
#      - '/etc/ghost/:/ghost-override'
#    environment:
#      PROXY_LOCATION: ghost
#      VIRTUAL_HOST: ghost.yourDomain.lan
#      VIRTUAL_PORT: 2368
#    restart: always
