version: "3"

#using reverse proxy
services:
  jwilder-proxy:
    image: budry/jwilder-nginx-proxy-arm
    container_name: jwilder_brudy_proxy_cn
    ports:
      - '80:80'
    environment:
      DEFAULT_HOST: ${PIHOLE_LOCAL_DOMAIN}
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    restart: always

  pihole:
    image: pihole/pihole:latest
    container_name: pihole_og_cn
    dns:
      - 127.0.0.1
      - 9.9.9.9
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - "67:67/udp"
      - '${PIHOLE_PORT}:80/tcp'
      - "443:443/tcp"
    volumes:
      - '${EXT_HDD_MOUNT}/files/${PIHOLE_CONFIGS}/etc-pihole/:/etc/pihole/'
      - '${EXT_HDD_MOUNT}/files/${PIHOLE_CONFIGS}/etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # run `touch ./var-log/pihole.log` first unless you like errors
      - '${EXT_HDD_MOUNT}/files/${PIHOLE_CONFIGS}/var-log/pihole.log:/var/log/pihole.log'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    environment:
      ServerIP: ${SERVER_IP}
      TZ: 'Europe/London'
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: ${PIHOLE_LOCAL_DOMAIN}
      VIRTUAL_PORT: 80
    extra_hosts:
      # Resolve to nothing domains (terminate connection)
      - 'nw2master.bioware.com nwn2.master.gamespy.com:0.0.0.0'
      # LAN hostnames for other docker containers using jwilder
      - '${PIHOLE_LOCAL_DOMAIN}:${SERVER_IP}'
      - 'pihole ${PIHOLE_LOCAL_DOMAIN}:${SERVER_IP}'
      - 'nextcloud_app ${NEXTCLOUD_LOCAL_DOMAIN}:${SERVER_IP}'
      #- 'wordpress wordpress.yourDomain.lan:192.168.41.55'
    restart: always
  postgres_db:
    image: postgres
    container_name: postgres_db_cn
    restart: always
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_VAR}
      - POSTGRES_HOST=localhost
  nextcloud_app:
    image: nextcloud
    container_name: nextcloud_og_cn
    restart: always
    ports:
      - ${NEXTCLOUD_PORT}:80
    volumes:
      - ${NEXTCLOUD_DATA}:/var/www/html
      #- ${EXT_HDD_MOUNT}/files/${NEXTCLOUD_DATA}/config:/var/www/html/config
      - ${EXT_HDD_MOUNT}/files/${NEXTCLOUD_DATA}/data:/var/www/html/data:rw
      - ${EXT_HDD_MOUNT}/entertainment:/media/entertainment:rw
      - ${EXT_HDD_MOUNT}/softwares:/media/softwares:rw
      - ${EXT_HDD_MOUNT}/files/user_space:/media/files:rw
    environment:
      ServerIP: ${SERVER_IP}
      PROXY_LOCATION: nextcloud_app
      VIRTUAL_HOST: ${NEXTCLOUD_LOCAL_DOMAIN}
      VIRTUAL_PORT: 80
    depends_on:
      - postgres_db
