version: "3"
services:
  jwilder-proxy:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
    environment:
      DEFAULT_HOST: ${PIHOLE_LOCAL_DOMAIN}
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    restart: always
    
  pihole:
    image: pihole/pihole:latest
    container_name: pihole2_og_cn
    dns:
      - 127.0.0.1
      - 9.9.9.9
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - "67:67/udp"
      - '${PIHOLE_PORT}:80/tcp'
      - "443:443/tcp"
    volumes:
      - '${PIHOLE_CONFIGS}/etc-pihole/:/etc/pihole/'
      - '${PIHOLE_CONFIGS}/etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # run `touch ./var-log/pihole.log` first unless you like errors
      #- './pihole_configs/var-log/pihole.log:/var/log/pihole.log'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    environment:
      ServerIP: ${SERVER_IP}
      TZ: 'Europe/London'
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD}
      PROXY_LOCATION: pihole
      VIRTUAL_HOST: ${PIHOLE_LOCAL_DOMAIN}
      VIRTUAL_PORT: 80
    extra_hosts:
      # Resolve to nothing domains (terminate connection)
      - 'nw2master.bioware.com nwn2.master.gamespy.com:0.0.0.0'
      # LAN hostnames for other docker containers using jwilder
      - 'pihole.local:${SERVER_IP}'
      - 'pihole pihole.local:${SERVER_IP}'
      - 'transmission_app transmission_app.local:${SERVER_IP}'
      #- 'wordpress wordpress.yourDomain.lan:192.168.41.55'
    restart: always
    
  transmission:
    image: linuxserver/transmission
    container_name: transmission_cn
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=Europe/London
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
      #- USER=username #optional
      #- PASS=password #optional
      #- PROXY_LOCATION: transmission
      #- VIRTUAL_HOST: ${TRANSMISSION_LOCAL_DOMAIN}
      #- VIRTUAL_PORT: 80
    volumes:
      - ${TRANSMISSION_DATA}/config:/config
      - ${EXT_HDD_MOUNT}/downloads:/downloads
      - ${TRANSMISSION_DATA}/watch:/watch
    ports:
      - 8082:9091
      - 51413:51413
      - 51413:51413/udp
    restart: always
    
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
